language: python

cache: pip

python:
    - "3.6"
    - "3.7-dev"

install:
    - pip install -r requirements.txt

script:
      - pytest --ignore venv -W ignore::DeprecationWarning --cov=starlette_jwt --cov=tests --cov-fail-under=95 --cov-report=term-missing

after_script:
    - codecov